version: "2.1"
services:
  config-service:
    build: config-service
    ports:
      - 8081:8080

  discovery-service:
    build: discovery-service

  gateway:
    build: gateway

  auth-service:
    build: auth-service

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  form-service:
    build: form-service

  form-mongodb:
    build: mongodb
    ports:
      - 25001:27017